language: python

python:
  - "3.5.2"

services: postgresql

env:
  - DJANGO=1.10.2

branches:
  only:
    - master
    - development

before_install:
  - export PYTHONPATH=$HOME/builds/benjaminhadfield/tripplanner

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test --noinput

after_script:
  - echo "travis complete"